### PR TITLE
fix: prevent pollution with @types/node by using @types/events directly

### LINKED ISSUE #1361: @types/node pollution
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

Unnecessary

### Reproduction steps

Just import msw in a typescript project

### Current behavior

Import `msw` will also import `@types/node` which pollutes types.

For example, after import `msw`, type of `setTimeout` is no longer correct:

image

This issue results from type declaration of [`strict-event-emitter`](https://unpkg.com/browse/strict-event-emitter@0.2.4/lib/StrictEventEmitter.d.ts):

image

Removing the first line can fix the bug.

### Expected behavior

Not import types of node when using the library in a browser

### PR DESCRIPTION
**Pull request by jkieboom**
Fixes https://github.com/mswjs/msw/issues/1361.

### CODE REVIEW

**Comment by jkieboom** [comment]
Ping @kettanaito

**Comment by kettanaito** [comment]
This looks good by me but I'm curious if you're solving any particular issue by this, @jkieboom? If so, could you please briefly describe/reference it? It'd help a lot for posterity. 

I suspect this may have something to do with Node types pollution in MSW but I'd like to hear from you.

**Comment by jkieboom** [comment]
Yes, this solves the types pollution issue. I linked to this PR from that issue

**Comment by kettanaito** [comment]
Fantastic! Thank you for looking into this. 

GitHub Actions seems to be having a bad time this morning. Let's wait for them to be up so we could see the CI status before merging.

**Comment by kettanaito** [comment]
## Released: v0.2.7 🎉

This has been released in v0.2.7!

- 📄 [**Release notes**](https://github.com/open-draft/strict-event-emitter/releases/tag/v0.2.7)
- 📦 [npm package](https://www.npmjs.com/package/strict-event-emitter/v/0.2.7)

Make sure to always update to the latest version (`npm i strict-event-emitter@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by kettanaito** [comment]
Thanks for improving this, @jkieboom! 

I'm considering deprecating this library so it wouldn't have a runtime element. One can augment any type in TypeScript just by including a `.d.ts` file. I think that's the way to go to provide some standard API like `EventEmitter` with better type safety. I'm exploring this right now and, hopefully, will introduce the change sometime soon.

**Pull request merged**
